### ISSUE TITLE
视频只分屏 不360°变换

### ISSUE THREAD

**Issue by chenwulue** [substarry/VRPlayer#3]
请问一下，怎么让这个视频只分成左右两屏 但是不是360那种呢，类似橙子VR的左右3D格式

**Comment by substarry** [comment]
现在demo是用来播放360°视频的，不是播放3D视频的；
播放360°视频时在VideoRenderer中建了一个球（Sphere），并把360°视频贴在了上面，以此来实现，如下：

```
        mSphere = new Sphere(50, 64, 32);
        mSphere.setScaleX(-1);
        mSphere.setMaterial(material);

        getCurrentScene().addChild(mSphere);

        getCurrentCamera().setPosition(Vector3.ZERO);

        getCurrentCamera().setFieldOfView(75);
```

如果你要播放3D视频，建议你尝试在VideoRender中建一个平面（Plane），并把视频贴在平面上，应该可以实现，但是3D视频有各种格式，具体的很多参数怎么设置估计很难用这个Demo实现。
